version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  producer:
    image: python:3.10-slim
    container_name: kafka-producer
    depends_on:
      - kafka
    volumes:
      - ./kafka:/app/kafka
      - ./data:/app/data
    working_dir: /app
    command: >
      sh -c "pip install pandas kafka-python &&
             python kafka/producer.py"

  consumer:
    image: python:3.10-slim
    container_name: kafka-consumer
    depends_on:
      - kafka
      - minio
    volumes:
      - ./kafka:/app/kafka
      - ./data:/app/data
    working_dir: /app
    command: >
      sh -c "pip install kafka-python boto3 pandas minio &&
             python kafka/consumer.py"

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"

  spark-trainer:
    image: bitnami/spark:latest
    container_name: spark-trainer
    depends_on:
      - minio
    volumes:
      - ./training:/app/training
    working_dir: /app
    command: >
      bash -c "pip install minio &&
               spark-submit training/train_model.py"

  dashboard:
    image: python:3.10-slim
    container_name: dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./dashboard:/app
    working_dir: /app
    depends_on:
      - minio
    command: >
      sh -c "pip install streamlit pandas minio pyspark &&
            streamlit run app.py --server.port=8501 --server.address=0.0.0.0"

volumes:
  minio-data:
